name: Sync Gitea to GitHub (HTTPS)

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分钟执行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          ref: main  # 要同步的目标分支
          fetch-depth: 0  # 获取完整的提交历史，避免分支分叉问题

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Gitea as remote (HTTPS)
        run: |
          # 添加 Gitea 为远程仓库，使用 HTTPS
          git remote add gitea https://${{ secrets.GITEA_USER }}:${{ secrets.GITEA_PASSWORD }}@git.sundays.ink/xiaochou164/clash_rule.git

      - name: Fetch from Gitea
        run: git fetch gitea

      - name: Pull GitHub's main branch (with merge strategy)
        run: |
          # 拉取 GitHub 的 main 分支，使用 merge 策略，避免分叉问题
          git pull --no-ff origin main

      - name: Merge Gitea's main branch into GitHub's main
        run: |
          # 合并 Gitea 的 main 分支到当前分支（GitHub 的 main）
          git merge gitea/main --no-ff

      - name: Push to GitHub
        run: |
          # 设置 GitHub 为远程仓库（使用 PAT）
          git remote set-url origin https://x-access-token:${{ secrets.GITHUBACCESS_TOKEN }}@github.com/xiaochou164/clash_rule.git

          # 推送合并后的代码到 GitHub 的 main 分支
          git push origin main
