name: Sync Gitea to GitHub (HTTPS)

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分钟执行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gitea repo
        run: |
          # 从 Gitea 克隆代码到当前目录
          git clone https://${{ secrets.GITEA_USER }}:${{ secrets.GITEA_PASSWORD }}@git.sundays.ink/xiaochou164/clash_rule.git
          # 进入克隆下来的仓库目录
          cd clash_rule
          git init

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitHub as remote (HTTPS)
        run: |
          # 设置 GitHub 为远程仓库
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/xiaochou164/clash_rule.git

      - name: Push to GitHub
        run: |
          # 推送当前代码到 GitHub 的 main 分支
          git push origin main --force
